import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Linear Digital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="preloader">
          <div id="loader" className="loader">
            <div className="loader-container">
              <div className="loader-icon"><img src="/assets/img/preloader.png" alt="Linear Digital" />
              </div>
            </div>
          </div>
        </div>
        {children}

        <script src="/assets/js/vendor/jquery-3.6.0.min.js"></script>
        <script src="/assets/js/bootstrap.min.js"></script>
        <script src="/assets/js/isotope.pkgd.min.js"></script>
        <script src="/assets/js/imagesloaded.pkgd.min.js"></script>
        <script src="/assets/js/jquery.magnific-popup.min.js"></script>
        <script src="/assets/js/jquery.odometer.min.js"></script>
        <script src="/assets/js/swiper-bundle.min.js"></script>
        <script src="/assets/js/jquery.appear.js"></script>
        <script src="/assets/js/slick.min.js"></script>
        <script src="/assets/js/ajax-form.js"></script>
        <script src="/assets/js/parallax.min.js"></script>
        <script src="/assets/js/jquery.parallaxScroll.min.js"></script>
        <script src="/assets/js/tween-max.js"></script>
        <script src="/assets/js/wow.min.js"></script>
        <script src="/assets/js/main.js"></script>
      </body>
    </html>
  );
}
